/* ============================================================
   DW_FEATS — Deathwatch feat catalog
   Single source of truth — Feats.html renders its cards from
   this file, and deathwatch_character_sheet.html uses it for
   the feat picker, half-feat +1 grants, and use tracking.
   Fields: id, name, cat, type (full|half),
     half: ability options for the +1 (['str',...] or 'any'),
     prereq: prerequisite text ('' = none),
     uses: {n: count | 'pb', per: 'resupply' | 'short', label?},
     dice: rollable effect string for Quick Actions,
     desc: rules text (may contain <strong> markup).
   ============================================================ */
const DW_FEAT_CATS = [
  {id: "general", label: "General",
   note: "Open to any Deathwatch operative \u2014 no prerequisite beyond what's noted."},
  {id: "armor", label: "Defense & Armor",
   note: "Grants or refines proficiency with a specific Armor Pattern. Certification feats let you cross-train into a heavier pattern than your class normally allows; Mastery feats reward a character already proficient with one."},
  {id: "marksman", label: "Marksman",
   note: "Requires proficiency with at least one Primary or Secondary Ranged weapon."},
  {id: "melee", label: "Melee & Brawler",
   note: "Requires proficiency with at least one melee weapon or unarmed strikes, unless noted otherwise."},
  {id: "faith", label: "Faith & Resolve",
   note: "Requires Wisdom or Charisma 13+."},
  {id: "psyker", label: "Psyker",
   note: "Requires the ability to manifest Warp Powers (e.g. the Librarian class, or GM-approved psychic potential)."},
  {id: "tech", label: "Tech-Adept",
   note: "No prerequisite unless noted; most useful to Techmarines and Tech-Priests."},
  {id: "apothecary", label: "Apothecary",
   note: "No prerequisite; built around access to medicae supplies."},
  {id: "infiltration", label: "Infiltration",
   note: "Requires proficiency with Phobos Armor, or the Vanguard Operative, Assassin, or Close Combat Operative class."},
];

const DW_FEATS = [
  {id: "combat-reflexes",
   name: "Combat Reflexes",
   cat: "general",
   type: "full",
   desc: "You gain a <strong>+5 bonus to initiative</strong>. You can't be surprised while you are conscious."},
  {id: "iron-constitution",
   name: "Iron Constitution",
   cat: "general",
   type: "full",
   desc: "Your hit point maximum increases by an amount equal to <strong>twice your character level</strong> when you take this feat. Whenever you gain a level thereafter, your hit point maximum increases by an additional <strong>2 hit points</strong>."},
  {id: "fortunes-grace",
   name: "Fortune's Grace",
   cat: "general",
   type: "full",
   uses: {n: 3, per: "resupply", label: "Luck Points"},
   desc: "You have <strong>3 luck points</strong>. Whenever you make an attack roll, ability check, or saving throw, you may spend one to roll an additional d20 and choose which result to use. You may also spend one when a creature attacks you, rolling a d20 and choosing whether it or the attacker's roll is used. Expended points return after a resupply."},
  {id: "void-forged-reflexes",
   name: "Void-Forged Reflexes",
   cat: "general",
   type: "full",
   desc: "Your speed increases by <strong>10 ft</strong>. Difficult terrain no longer costs you extra movement when you Dash. When you make a melee attack against a creature, you don't provoke opportunity attacks from that creature for the rest of the turn, whether you hit or not."},
  {id: "watchful-guardian",
   name: "Watchful Guardian",
   cat: "general",
   type: "full",
   desc: "Hitting a creature with an opportunity attack reduces its speed to <strong>0</strong> for the rest of the turn. Creatures provoke an opportunity attack from you even when they Disengage. When a creature within 5 ft of you attacks a target other than you, you may use your reaction to make a melee weapon attack against the attacker."},
  {id: "merciless-strike",
   name: "Merciless Strike",
   cat: "general",
   type: "full",
   desc: "Once per turn when you roll damage for a melee weapon attack, you may reroll the weapon's damage dice and use either total."},
  {id: "shadow-discipline",
   name: "Shadow Discipline",
   cat: "general",
   type: "full",
   desc: "You are proficient in Stealth. You can attempt to hide when only lightly obscured. If you're hidden from a creature and miss it with a ranged attack, the attack doesn't reveal your position. Dim light no longer imposes disadvantage on your Perception checks relying on sight."},
  {id: "hardened-frame",
   name: "Hardened Frame",
   cat: "general",
   type: "half",
   half: ["con"],
   desc: "Increase your <strong>Constitution by 1</strong>. Whenever you roll a Hit Die to regain hit points, the minimum you regain equals twice your Constitution modifier (minimum of 2)."},
  {id: "steadfast-resolve",
   name: "Steadfast Resolve",
   cat: "general",
   type: "half",
   half: "any",
   desc: "Choose one ability score and increase it by <strong>1</strong>. You gain proficiency in saving throws using that ability."},
  {id: "adept-of-many-trades",
   name: "Adept of Many Trades",
   cat: "general",
   type: "full",
   desc: "You gain proficiency in any combination of <strong>three skills or tools</strong> of your choice."},
  {id: "battlefield-awareness",
   name: "Battlefield Awareness",
   cat: "general",
   type: "half",
   half: ["int", "wis"],
   desc: "Increase your <strong>Intelligence or Wisdom by 1</strong>. If you can see a creature's mouth as it speaks a language you understand, you can read its lips. You gain a <strong>+5 bonus</strong> to passive Perception and passive Investigation."},
  {id: "riposte-discipline",
   name: "Riposte Discipline",
   cat: "general",
   type: "full",
   prereq: "Strength or Dexterity 13+, and proficiency with at least one melee weapon.",
   desc: "When a creature hits you with a melee attack roll, you may use your reaction to add your <strong>Proficiency Bonus to AC</strong> against that attack, potentially causing it to miss, provided you're wielding a melee weapon you're proficient with."},
  {id: "combat-discipline",
   name: "Combat Discipline",
   cat: "general",
   type: "full",
   prereq: "proficiency with at least one weapon.",
   desc: "Choose one technique you don't already have from another source: <strong>Archery</strong> (+2 to ranged attack rolls); <strong>Defense</strong> (+1 AC while wearing armor); <strong>Dueling</strong> (+2 damage with a one-handed melee weapon wielded with no other weapon in your other hand); <strong>Great Weapon Fighting</strong> (reroll 1s and 2s on damage dice for two-handed melee weapons, must use the new roll); <strong>Two-Weapon Fighting</strong> (add your ability modifier to your off-hand attack's damage when fighting with two weapons)."},
  {id: "void-shield-tactics",
   name: "Void-Shield Tactics",
   cat: "general",
   type: "full",
   prereq: "proficiency with shields.",
   desc: "If you take the Attack action, you may use a bonus action to shove a creature within 5 ft with your shield. While not incapacitated, add your shield's AC bonus to Dexterity saving throws against effects that target only you."},
  {id: "twin-blade-adept",
   name: "Twin-Blade Adept",
   cat: "general",
   type: "full",
   desc: "You gain <strong>+1 AC</strong> while wielding two melee weapons. You can use two-weapon fighting even when the one-handed melee weapons you wield aren't Light. You can draw or stow two one-handed weapons when you'd normally be able to draw or stow only one."},
  {id: "void-runners-athleticism",
   name: "Void-Runner's Athleticism",
   cat: "general",
   type: "half",
   half: ["str", "dex"],
   desc: "Increase your <strong>Strength or Dexterity by 1</strong>. Standing up from prone costs only 5 ft of movement. Climbing no longer costs extra movement. You can make a running long or high jump after moving only 5 ft, rather than 10."},
  {id: "tacticus-certification",
   name: "Tacticus Certification",
   cat: "armor",
   type: "half",
   half: ["str", "con"],
   prereq: "proficiency with Phobos Armor.",
   desc: "Increase your <strong>Strength or Constitution by 1</strong>. You gain proficiency with Tacticus Armor and with shields."},
  {id: "gravis-certification",
   name: "Gravis Certification",
   cat: "armor",
   type: "half",
   half: ["str"],
   prereq: "proficiency with Tacticus Armor, Strength 13+.",
   desc: "Increase your <strong>Strength by 1</strong>. You gain proficiency with Gravis Armor."},
  {id: "tacticus-armor-mastery",
   name: "Tacticus Armor Mastery",
   cat: "armor",
   type: "full",
   prereq: "proficiency with Tacticus Armor.",
   desc: "While wearing Tacticus Armor, you may add your Dexterity modifier (to a maximum of <strong>+2</strong>) to your AC, and you suffer no penalty to Stealth checks from wearing it."},
  {id: "gravis-armor-mastery",
   name: "Gravis Armor Mastery",
   cat: "armor",
   type: "half",
   half: ["str"],
   prereq: "proficiency with Gravis Armor.",
   desc: "Increase your <strong>Strength by 1</strong>. While wearing Gravis Armor, damage you take from nonmagical Bludgeoning, Piercing, and Slashing attacks is reduced by <strong>3</strong>."},
  {id: "void-range-precision",
   name: "Void-Range Precision",
   cat: "marksman",
   type: "full",
   desc: "Your ranged weapon attacks no longer suffer disadvantage from long range. Before making an attack with a ranged weapon you're proficient with, you may take a <strong>-5 penalty</strong> to the attack roll; if the attack hits, deal an additional <strong>+10 damage</strong>."},
  {id: "close-quarters-marksman",
   name: "Close-Quarters Marksman",
   cat: "marksman",
   type: "full",
   desc: "You suffer no disadvantage on ranged weapon attack rolls from having a hostile creature within 5 ft of you. When you take the Attack action and attack with a Primary or Secondary Ranged weapon, you may use a bonus action to make one attack with a different Secondary Ranged weapon you're holding."},
  {id: "called-shot",
   name: "Called Shot",
   cat: "marksman",
   type: "half",
   half: ["str", "dex"],
   prereq: "proficiency with a weapon dealing Piercing damage.",
   desc: "Increase your <strong>Strength or Dexterity by 1</strong>. Once per turn when you hit with a Piercing weapon, reroll one damage die and use the new result. On a critical hit with a Piercing weapon, roll one additional damage die of its type."},
  {id: "executioners-fury",
   name: "Executioner's Fury",
   cat: "melee",
   type: "full",
   prereq: "proficiency with a melee weapon dealing 1d8 or larger damage, or with the Two Handed or Locked In property.",
   desc: "When you score a critical hit or reduce a creature to 0 HP with such a weapon, you may make one melee weapon attack as a bonus action. Before attacking with a qualifying weapon, you may take a <strong>-5 penalty</strong> to the roll for <strong>+10 damage</strong> on a hit."},
  {id: "reach-discipline",
   name: "Reach Discipline",
   cat: "melee",
   type: "full",
   prereq: "proficiency with a weapon that has the Reach property (e.g. Force Staff, Omnissian Power Axe, Servo-Arm).",
   desc: "When you take the Attack action with such a weapon, you may use a bonus action to attack with the opposite end, dealing 1d4 + Strength bludgeoning damage. You may make an opportunity attack against a creature that enters your reach, not just when it leaves."},
  {id: "close-quarters-fighter",
   name: "Close Quarters Fighter",
   cat: "melee",
   type: "half",
   half: ["str", "con"],
   desc: "Increase your <strong>Strength or Constitution by 1</strong>. You're proficient with improvised weapons and unarmed strikes; your unarmed strike deals 1d4 + Strength bludgeoning damage. When you hit with an unarmed strike or improvised weapon, you may use a bonus action to attempt to grapple the target."},
  {id: "headlong-assault",
   name: "Headlong Assault",
   cat: "melee",
   type: "full",
   desc: "When you Dash and move at least 10 ft in a straight line, you may use a bonus action to make one melee weapon attack. Choose one: gain a <strong>+5 bonus</strong> to that attack's damage roll, or the target must succeed on a Strength save (DC = 8 + Proficiency Bonus + Strength modifier) or be pushed 10 ft and knocked prone."},
  {id: "warp-hunter",
   name: "Warp-Hunter",
   cat: "melee",
   type: "full",
   desc: "You have advantage on saving throws against spells and Warp Powers manifested by creatures within 5 ft of you. When such a creature manifests a power within 5 ft of you, you may use your reaction to make a melee attack against it. If you damage a creature concentrating on a power or spell, it has disadvantage on the save to maintain concentration."},
  {id: "zealous-conviction",
   name: "Zealous Conviction",
   cat: "faith",
   type: "full",
   uses: {n: 1, per: "short"},
   desc: "As an action, spend 10 minutes leading up to six creatures within 30 ft (including yourself) through a rite of oath and remembrance. Each gains temporary hit points equal to your <strong>level + your Wisdom or Charisma modifier</strong>. A creature can't benefit again until it finishes a short or long rest (resupply)."},
  {id: "unshaken-faith",
   name: "Unshaken Faith",
   cat: "faith",
   type: "full",
   uses: {n: 1, per: "resupply"},
   desc: "You have advantage on saving throws against being Frightened. Once per resupply, when you fail a save against being Frightened or Charmed, you may reroll it, adding your Wisdom or Charisma modifier to the new result."},
  {id: "latent-psychic-spark",
   name: "Latent Psychic Spark",
   cat: "psyker",
   type: "full",
   uses: {n: 1, per: "resupply"},
   desc: "Choose one Rank I Warp Power from the Librarian's power list (not one of the free base powers). You learn it and can manifest it once without expending your normal resources, regaining that use after a long rest (resupply). If you already manifest Warp Powers, you may instead expend your existing resources to manifest it freely."},
  {id: "ward-of-the-immaterium",
   name: "Ward of the Immaterium",
   cat: "psyker",
   type: "full",
   desc: "You have advantage on Constitution saves to maintain concentration on a Warp Power when damaged. You can perform a power's somatic components even with your hands full. When a creature's movement provokes an opportunity attack, you may manifest a Warp Power with a casting time of one action at it instead of attacking, if the power could target only that creature."},
  {id: "machine-empathy",
   name: "Machine Empathy",
   cat: "tech",
   type: "full",
   uses: {n: "pb", per: "resupply"},
   dice: "Heals 2d6 HP",
   desc: "You gain proficiency with one type of artisan's tools. With 1 minute of work and the proper tools, you can restore 2d6 HP to a construct or vehicle, or clear one malfunction condition afflicting it \u2014 a number of times per resupply equal to your Proficiency Bonus. This is field first-aid, not a Techmarine's expertise: it grants no special advantage on repair or diagnostic checks themselves."},
  {id: "auxiliary-mechadendrite-training",
   name: "Auxiliary Mechadendrite Training",
   cat: "tech",
   type: "full",
   prereq: "Techmarine or Tech-Priest class.",
   desc: "Once on each of your turns, use a bonus action to take the Use an Object action or make one tool check, Investigation check, or repair attempt via your mechadendrites, without needing a free hand. If you own a Servo-Arm or Mechadendrites, their attacks count as magical for overcoming resistance and immunity."},
  {id: "battlefield-surgeon",
   name: "Battlefield Surgeon",
   cat: "apothecary",
   type: "full",
   dice: "Heals 1d6+4 HP",
   desc: "Stabilising a dying creature with a Narthecium or medicae supplies also restores 1 HP to it. As an action, expend one use of medicae supplies to restore <strong>1d6 + 4 HP</strong> to a creature within 5 ft, plus additional HP equal to its total Hit Dice. That creature can't benefit again until a short or long rest."},
  {id: "field-triage-reflex",
   name: "Field Triage Reflex",
   cat: "apothecary",
   type: "full",
   uses: {n: 1, per: "short"},
   desc: "Once per short rest, when an ally within 5 ft of you drops to 0 HP without being killed outright, you may use your reaction to have them spend one Hit Die, regaining HP as if they'd spent it during a short rest."},
  {id: "shadowed-ambusher",
   name: "Shadowed Ambusher",
   cat: "infiltration",
   type: "full",
   desc: "You have advantage on the first attack roll you make against any creature that hasn't yet taken a turn in the current combat. You may take the Hide action as a bonus action on each of your turns."},
];

function dwFeatById(id) {
  return DW_FEATS.find(function(f){ return f.id === id; }) || null;
}
